export const login = '/login'
export const save = '/save/'
export const menu = '/menu'
export const newblog = '/newblog'
export const posts = '/posts/'
export const blogcaches = '/blogcaches'
export const regist = '/regist'
export const checkemail = '/checkemail'
